### PR TITLE
Trim dependencies, add base  module, update docs

### PR DESCRIPTION
**Pull request by paf31**
/cc @jdegoes @garyb

### CODE REVIEW

**Comment by paf31** [comment]
I didn't regenerate docs yet, by the way, since I don't yet have Gulp working with 0.7.

Not sure if we want to try to generate docs for all dependencies using the new `psc-docs` or not.

**Comment by paf31** [comment]
Ok, docs are updated now.

**Comment by paf31** [comment]
Any more thoughts on this?

**Comment by jdegoes** [comment]
:+1:

**Comment by paf31** [comment]
Thanks! Just `channels` to update in `contrib` now, I'll try to get a PR together soon.

**Pull request merged**
