### PR TITLE
Updates for 1.0 core libraries

### PR DESCRIPTION
**Pull request by paf31**
cc @jdegoes. I fixed the warnings by adding explicit imports, but there might be other things you want to import now, I'm not sure. Also, I haven't updated the Travis build yet. If you like, I could switch the build to use Pulp?

Thanks.

### CODE REVIEW

**Comment by jdegoes** [comment]
@paf31 This looks great! Yes, switching the build to use pulp would be awesome. 🙏

**Comment by paf31** [comment]
I just copied a default Pulp script over, so it should hopefully work.

**Comment by paf31** [comment]
The build is passing now.

**Comment by jdegoes** [comment]
Thanks, this is hugely helpful! 👍

**Pull request merged**
