### PR TITLE
Update dependencies to latest versions; add Travis integration

### LINKED ISSUE #6: Bump at least purescript-strings, purescript-enums
Doing this will alleviate a number of unfortunate explicit resolutions in various packages.

### PR DESCRIPTION
**Pull request by jonsterling**
- added working Travis CI configuration (someone with admin access to this organization will need to turn it on, but it has succeeded in my fork)
- updated package dependencies
- updated dev dependencies

The gulpfile was using a very old version of `gulp-purescript`; I've updated it to use the latest one.  I had to write some new code to get the docs for the dependencies generated properly; along with the change, I made the docs end in `.md` rather than `.purs`.

Resolves #6

### CODE REVIEW

**Comment by garyb** [comment]
Looks good. Only thing I see missing is you could add yourself to the contributors. :smile:

**Comment by paf31** [comment]
Not a review of this change per se (which looks good to me, by the way), but @garyb recently added selective re-exports I think (only re-export what was imported), which might be useful for `purescript-base`. Specifically, more things might be exported since we can avoid name conflicts now.

**Comment by garyb** [comment]
Good point!

I need to document the exact ins and outs of the imports/exports now, but in brief:
- If you selectively import from module A into X, and then have X re-export A, only the imported members are re-exported
- You can export "pseudo modules" that exist due to being imported qualified now
- You can combine the two things to import from A, as well as selectively importing from A qualified as B, and then re-export B to only export the things listed in the qualified list:

``` purescript
module X (module B) where
  import A (w, x, y, z)
  import qualified A (x, y) as B
```

**Comment by garyb** [comment]
@paf31 I'm faffing around with a version of `Prelude` that is module-ified currently too, I'll open a PR for discussion once I'm done.

**Pull request merged**
